version: "3"
services:
    # start the ganache cli container
    ganache-cli:
        container_name: ganache-cli
        build:
            context: ./docker/ganache-cli
        restart: always
    brownie:
        depends_on:
            - ganache-cli
        container_name: brownie
        build:
            context: ./docker/brownie
        volumes:
            - "./workspace:/usr/src/app"
        environment:
            WEB3_INFURA_PROJECT_ID: ${WEB3_INFURA_PROJECT_ID}
        stdin_open: true # docker run -i
        tty: true # docker run -t
        restart: always
